test: fail if file does not exist (#2369)
Given we run test locally and that this does not change often one can
just run the command once in a while to fix the local setup.

```sh
Failed tests:

✖ matches snapshot if exists (0.78188ms)
  Error: THIRD_PARTY_NOTICES does not exist, run `npm ci && npm run bundle`
      at TestContext.<anonymous> (file:///usr/local/google/home/nvitkov/chrome-devtools-mcp/build/tests/third_party_notices.test.js:13:19)
      at Test.runInAsyncScope (node:async_hooks:227:14)
      at Test.run (node:internal/test_runner/test:1325:25)
      at Test.start (node:internal/test_runner/test:1191:17)
      at node:internal/test_runner/test:1792:71
      at node:internal/per_context/primordials:466:82
      at new Promise (<anonymous>)
      at new SafePromise (node:internal/per_context/primordials:435:3)
      at node:internal/per_context/primordials:466:9
      at Array.map (<anonymous>)
✖ THIRD_PARTY_NOTICES (1.41613ms)
  '1 subtest failed'
  
 ```